apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: default
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: gcr.io/trash-362115/ngrok:latest
        imagePullPolicy: IfNotPresent
        args:
          - "http"
          - "--url=your-ngrok-domain.ngrok.ngrok-free.app"
          - "chatbot-svc:8000"
        env:
          - name: NGROK_AUTHTOKEN
            valueFrom:
              secretKeyRef:
                name: ngrok-secret
                key: NGROK_AUTHTOKEN
        ports:
          - containerPort: 4040
---
apiVersion: v1
kind: Secret
metadata:
  name: ngrok-secret
type: Opaque
data:
  NGROK_AUTHTOKEN:
