apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: default
  labels:
    app: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: gcr.io/trash-362115/chatbot-svc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc
  labels:
    app: chatbot
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: chatbot
