version: "3.8"

services:
  chat-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    depends_on:
      - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: ["http", "--url=your-ngrok-domain.ngrok.ngrok-free.app", "chat-app:8000"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    ports:
      - "4040:4040"
